using System;
using UnityEngine;
using System.IO;
using UnityEditor;

namespace REFU
{
    public class TypeFieldInfo
    {
        public string FieldName;
        public Type FieldType;
    }

    public class CodeGenerator
    {
        static string CodeGeneratePath { get { return Application.dataPath + "/REFUGenCodes/"; } }

        public static void CreateType(string SourcefileName, string typeName, TypeFieldInfo[] typeFields, string use_namespace = "")
        {
            string gen_path = CodeGeneratePath + SourcefileName + "/";
            //if (!string.IsNullOrEmpty(use_namespace))
            //{
            //    gen_path += use_namespace + "/";
            //}

            if (!Directory.Exists(gen_path))
                Directory.CreateDirectory(gen_path);

            using (var sw = File.CreateText(gen_path + typeName + ".cs"))
            {
                sw.WriteLine("/**** Auto-Generated By REFU,Don't Modify it Manually ****/");
                sw.WriteLine("using UnityEngine;\n" +
                    "using System.Collections.Generic;\n");

                if (!string.IsNullOrEmpty(use_namespace))
                {
                    sw.WriteLine("//Use Sourcefile Name as Namespace");
                    sw.WriteLine("namespace " + use_namespace + " {");
                }

                sw.WriteLine("//Generated by Sheet : " + typeName);
                sw.WriteLine("public class " + typeName + " : ScriptableObject {");

                if (typeFields != null)
                {
                    foreach (var fieldInfo in typeFields)
                    {
                        if (fieldInfo.FieldType == null)
                        {
                            Debug.LogError("Can't Map Field Type : " + fieldInfo.FieldName + " by " + typeName);
                            continue;
                        }
                        sw.WriteLine(string.Format("    //Auto-Generated Field : {0}", fieldInfo.FieldName));
                        sw.WriteLine(string.Format("    public {0}[] {1};\n", fieldInfo.FieldType, fieldInfo.FieldName, fieldInfo.FieldType));
                    }
                }
                sw.WriteLine("}");

                if (!string.IsNullOrEmpty(use_namespace))
                    sw.WriteLine("}");

                sw.Flush();
            }

            AssetDatabase.Refresh();
        }
    }
}
