/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
using System.Runtime.CompilerServices;

namespace SampleECS
{
	public partial class ECS_Entity
	{
		const int INVAILD_IDX = -1;
		/* Component Code : TestComp */
		int _TestComp_pid = -1;
		public TestComp testcomp{ get { return context.pool_TestComp.use_coms[_TestComp_pid].user_struct; } }
		public bool has_TestComp { get { return _TestComp_pid != INVAILD_IDX; } }
		public void Add_TestComp(TestComp com) { if(_TestComp_pid == INVAILD_IDX) {_TestComp_pid = context.pool_TestComp.NewComponent(com); context.OnEntityChange(this); } }	
		public bool is_TestComp_dirty{ get { if(_TestComp_pid == INVAILD_IDX) return false; return context.pool_TestComp.use_coms[_TestComp_pid]._dirty; } }
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public void Replace_TestComp(TestComp com) { context.pool_TestComp.SetDirty(_TestComp_pid, com); }

		/* Component Code : test_struct */
		int _test_struct_pid = -1;
		public test_struct test_struct{ get { return context.pool_test_struct.use_coms[_test_struct_pid].user_struct; } }
		public bool has_test_struct { get { return _test_struct_pid != INVAILD_IDX; } }
		public void Add_test_struct(test_struct com) { if(_test_struct_pid == INVAILD_IDX) {_test_struct_pid = context.pool_test_struct.NewComponent(com); context.OnEntityChange(this); } }
		public bool is_test_struct_dirty{ get { if(_test_struct_pid == INVAILD_IDX) return false; return context.pool_test_struct.use_coms[_test_struct_pid]._dirty; } }
		public void Replace_test_struct(test_struct com) { context.pool_test_struct.SetDirty(_test_struct_pid, com); }

	}
}
