/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
using System.Collections.Generic;
namespace SampleECS
{
	public static partial class ECS_Component_Type
	{
		/* Component <TestComp> ID */
		public const int TestComp = 0;
	}

	public static partial class ECS_Component_Wrap
	{
		static bool inited = false;
		public static void Init()
		{
			if(inited) return;
			COM_TYPE_ID_MAP.Add("TestComp",ECS_Component_Type.TestComp);
			ECS_Component_Type.SetTypeCount(COM_TYPE_ID_MAP.Count);
			inited = true;
		}
	}
}
