/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
namespace SampleECS
{
	public class ECS_Game_Context : ECS_Context
	{
		public ECS_Game_Entity CreateEntity() { return __CreateEntity<ECS_Game_Entity>(); }

		/******** Begin Static Components Code ********/
		public MsgComp static_msgcomp = new MsgComp();
		public void Replace_MsgComp(MsgComp com) {
			static_msgcomp = com;
			if (ExcutingSystem) static_dirtyMarkBack[Game_Component_Type.Static_MsgComp] = FrameCount + 1;
			else static_dirtyMarkFront[Game_Component_Type.Static_MsgComp] = FrameCount;
		}
		public override void InitStaticCom() {
			static_dirtyMarkFront = new uint[Game_Component_Type.STATIC_TYPE_COUNT];
			static_dirtyMarkBack = new uint[Game_Component_Type.STATIC_TYPE_COUNT];
		}
		/******** End Static Components Code ********/

		public ECS_Component_Pool<IDComp> pool_IDComp;
		public ECS_Component_Pool<PositionComp> pool_PositionComp;
		public ECS_Component_Pool<TransformComp> pool_TransformComp;
		public ECS_Component_Pool<CreateComp> pool_CreateComp;
		public override void InitComPool(int context_id)
		{
			component_pool_container_ptr++;
			pool_IDComp = ECS_Component_Pool<IDComp>.GetPool(context_id,typeof(IDComp));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_IDComp);

			component_pool_container_ptr++;
			pool_PositionComp = ECS_Component_Pool<PositionComp>.GetPool(context_id,typeof(PositionComp));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_PositionComp);

			component_pool_container_ptr++;
			pool_TransformComp = ECS_Component_Pool<TransformComp>.GetPool(context_id,typeof(TransformComp));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_TransformComp);

			component_pool_container_ptr++;
			pool_CreateComp = ECS_Component_Pool<CreateComp>.GetPool(context_id,typeof(CreateComp));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_CreateComp);

		}
	}
}
