/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
namespace SampleECS
{
	/// <summary>
	/// System In "Game" Context
	/// </summary>
	public class ECS_Game_System : ECS_System
	{
		protected ECS_Game_Context context { get { return __context as ECS_Game_Context; } }

		public override bool __GetSystemMatch(ECS_Entity entity) {
			return GetSystemMatch(entity as ECS_Game_Entity);
		}
		public virtual bool GetSystemMatch(ECS_Game_Entity entity) { return true; }

		protected override void __OnSystemInited(ECS_Context context) {
			base.__OnSystemInited(context);
			OnSystemInited(context as ECS_Game_Context);
		}
		protected virtual void OnSystemInited(ECS_Game_Context context) { }

		public override void __Excute(ECS_Entity entity) {
			base.__Excute(entity);
			Excute(entity as ECS_Game_Entity);
		}
		public virtual void Excute(ECS_Game_Entity entity) { }

	}

	/// <summary>
	/// Static System In "Game" Context
	/// </summary>
	public class ECS_Game_Static_System : ECS_Static_System
	{
		public override void __ExcuteStatic(ECS_Context context)
		{
			base.__ExcuteStatic(context);
			ExcuteStatic(context as ECS_Game_Context);
		}
		public virtual void ExcuteStatic(ECS_Game_Context context) { }
	}
}
