/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
namespace SampleECS
{
	public partial class ECS_Context
	{
		public ECS_Component_Pool<TestComp> pool_TestComp;
		public ECS_Component_Pool<test_struct> pool_test_struct;
		public void InitComPool(int context_id)
		{
			component_pool_container_ptr++;
			pool_TestComp = ECS_Component_Pool<TestComp>.GetPool(context_id,typeof(TestComp));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_TestComp);

			component_pool_container_ptr++;
			pool_test_struct = ECS_Component_Pool<test_struct>.GetPool(context_id,typeof(test_struct));
			ECS_Utils.SetArrayElement(ref component_pool_container,component_pool_container_ptr,pool_test_struct);

		}
	}
}
