/*
	Auto Generated By SampleECS,Don't Modify It Manually!
*/
using System.Collections.Generic;
namespace SampleECS
{
	public static partial class ECS_Component_Type
	{
		/* Component <IDComp> ID */
		public const int IDComp = 0;
		/* Component <PositionComp> ID */
		public const int PositionComp = 1;
		/* Component <TransformComp> ID */
		public const int TransformComp = 2;
		/* Component <CreateComp> ID */
		public const int CreateComp = 3;
	}

	public static partial class ECS_Component_Wrap
	{
		static bool inited = false;
		public static void Init()
		{
			if(inited) return;
			COM_TYPE_ID_MAP.Add("IDComp",ECS_Component_Type.IDComp);
			COM_TYPE_ID_MAP.Add("PositionComp",ECS_Component_Type.PositionComp);
			COM_TYPE_ID_MAP.Add("TransformComp",ECS_Component_Type.TransformComp);
			COM_TYPE_ID_MAP.Add("CreateComp",ECS_Component_Type.CreateComp);
			ECS_Component_Type.SetTypeCount(COM_TYPE_ID_MAP.Count);
			inited = true;
		}
	}
}
